# Generated by Django 5.2.6 on 2025-10-12 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='detalles',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='id_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_items', to='principal.orden'),
        ),
    ]
