# Generated by Django 5.2.6 on 2025-10-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_orden_detalles_alter_detalleorden_id_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nombre_usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
