# Generated by Django 5.2.6 on 2025-10-12 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_orden_nombre_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='principal.usuario'),
        ),
    ]
