# Generated by Django 5.2.6 on 2025-10-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_orden_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='nombre_usuario',
            new_name='nombre_cliente',
        ),
    ]
