# Generated by Django 5.2.6 on 2025-10-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_rename_nombre_usuario_orden_nombre_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
