# Generated by Django 5.2.6 on 2025-10-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_orden_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='id_orden',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
