# Generated by Django 5.2.6 on 2025-10-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_orden_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='numero_orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
