# Generated by Django 5.2.6 on 2025-10-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_alter_orden_id_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='id_orden',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
