# Generated by Django 5.2.6 on 2025-10-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_orden_numero_orden'),
        ('principal', '0008_alter_orden_id_orden'),
    ]

    operations = [
    ]
