# Generated by Django 5.2.6 on 2025-10-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_merge_20251024_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10),
        ),
    ]
