# Generated by Django 5.2.6 on 2025-11-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_orden_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pago', 'Pago')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
