# Generated by Django 5.2.6 on 2025-11-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_alter_orden_estado_pago_alter_orden_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='oculta',
            field=models.BooleanField(default=False),
        ),
    ]
