# Generated by Django 5.2.6 on 2025-11-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_orden_oculta'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
    ]
